survos_tabler:
  auto_breadcrumbs: true
  #  auth_menu: true
  routes:
      login: app_login
      logout: app_logout
      register: app_register
      home: app_homepage
  menu_options:
      frontPage: false
      showAppMenu: false
  app:
    code: showcase
    abbr: <b>show</b>case
  options:
    # consider https://startbootstrap.com/previews/simple-sidebar as another theme
    theme: tabler
    layout: horizontal


#survos_velzon:
