<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * @return array<string, array{    // Import name as key, description of the imported file as value
 *     path: string,               // Logical, relative or absolute path to the file
 *     type?: 'js'|'css'|'json',   // Type of the file, defaults to 'js'
 *     entrypoint?: bool,          // Whether the file is an entrypoint, for 'js' only
 * }|array{
 *     version: string,            // Version of the remote package
 *     package_specifier?: string, // Remote "package-name/path" specifier, defaults to the import name
 *     type?: 'js'|'css'|'json',
 *     entrypoint?: bool,
 * }>
 */
return [
    'app' => ['path' => './assets/app.js', 'entrypoint' => true],
    'admin' => ['path' => './assets/admin.js', 'entrypoint' => true],
    '@symfony/stimulus-bundle' => ['path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js'],
    '@hotwired/stimulus' => ['version' => '3.2.2'],
    '@hotwired/turbo' => ['version' => '8.0.20'],
    'masonry' => ['version' => '0.0.2'],
    'outlayer' => ['version' => '2.1.1'],
    'get-size' => ['version' => '3.0.0'],
    'ev-emitter' => ['version' => '2.1.2'],
    'fizzy-ui-utils' => ['version' => '3.0.0'],
    '@tabler/core' => ['version' => '1.6.1'],
    '@tabler/core/dist/css/tabler.min.css' => ['version' => '1.6.1', 'type' => 'css'],
    'simple-datatables' => ['version' => '10.3.0'],
    'locutus/php/strings/sprintf' => ['version' => '2.0.32'],
    'locutus/php/strings/vsprintf' => ['version' => '2.0.32'],
    'locutus/php/math/round' => ['version' => '2.0.32'],
    'locutus/php/math/max' => ['version' => '2.0.32'],
    'locutus/php/math/min' => ['version' => '2.0.32'],
    'locutus/php/strings/strip_tags' => ['version' => '2.0.32'],
    'locutus/php/datetime/strtotime' => ['version' => '2.0.32'],
    'locutus/php/datetime/date' => ['version' => '2.0.32'],
    'locutus/php/var/boolval' => ['version' => '2.0.32'],
    'escape-html' => ['version' => '1.0.3'],
    'flag-icons' => ['version' => '7.5.0'],
    'flag-icons/css/flag-icons.min.css' => ['version' => '7.5.0', 'type' => 'css'],
    '@stimulus-components/dialog' => ['version' => '1.0.1'],
    '@andypf/json-viewer' => ['version' => '2.8.0'],
    'reveal.js' => ['version' => '6.0.1'],
    'reveal.js/dist/reveal.css' => ['version' => '6.0.1', 'type' => 'css'],
    'reveal.js/dist/theme/black.css' => ['version' => '6.0.1', 'type' => 'css'],
    'reveal.js/plugin/highlight' => ['version' => '6.0.1'],
    'reveal.js/dist/plugin/highlight/monokai.css' => ['version' => '6.0.1', 'type' => 'css'],
    'debug' => ['version' => '4.4.3'],
    'ms' => ['version' => '2.1.3'],
    'ai' => ['version' => '6.0.5'],
    'markdown-to-jsx' => ['version' => '7.7.17'],
    '@ai-sdk/gateway' => ['version' => '3.0.4'],
    '@ai-sdk/provider-utils' => ['version' => '4.0.2'],
    '@ai-sdk/provider' => ['version' => '3.0.1'],
    'zod/v4' => ['version' => '4.3.4'],
    '@opentelemetry/api' => ['version' => '1.9.0'],
    'react' => ['version' => '19.2.0'],
    '@vercel/oidc' => ['version' => '3.0.5'],
    'eventsource-parser/stream' => ['version' => '3.0.6'],
    'zod/v3' => ['version' => '4.3.4'],
    '@standard-schema/spec' => ['version' => '1.1.0'],
    'chart.js' => ['version' => '4.5.1'],
    '@kurkle/color' => ['version' => '0.3.4'],
    'dexie' => ['version' => '4.4.2'],
    '@tacman1123/twig-browser' => ['version' => '1.0.0'],
    '@tacman1123/twig-browser/src/compat/compileTwigBlocks.js' => ['version' => '1.0.0'],
    '@tacman1123/twig-browser/adapters/symfony' => ['version' => '1.0.0'],
    '@swc/helpers/esm/_sliced_to_array.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_to_consumable_array.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_define_property.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_extends.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_destructuring_empty.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_spread.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_spread_props.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_type_of.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_instanceof.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_object_without_properties.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_call_super.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_class_call_check.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_create_class.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_inherits.js' => ['version' => '0.5.18'],
    '@swc/helpers/esm/_wrap_native_super.js' => ['version' => '0.5.18'],
    '@symfony/ux-live-component' => ['path' => './vendor/symfony/ux-live-component/assets/dist/live_controller.js'],
    '@floating-ui/dom' => ['version' => '1.8.0'],
    '@floating-ui/core' => ['version' => '1.8.0'],
    '@floating-ui/utils' => ['version' => '0.2.12'],
    '@floating-ui/utils/dom' => ['version' => '0.2.12'],
    'marked' => ['version' => '18.0.9'],
    'simple-datatables/dist/style.min.css' => ['version' => '10.3.0', 'type' => 'css'],
    'instantsearch.js' => ['version' => '4.117.0'],
    'algoliasearch-helper' => ['version' => '3.29.3'],
    'algoliasearch-helper/types/algoliasearch.js' => ['version' => '3.29.3'],
    '@algolia/events' => ['version' => '4.0.1'],
    'qs' => ['version' => '6.16.0'],
    'side-channel' => ['version' => '1.1.1'],
    'es-define-property' => ['version' => '1.0.1'],
    'es-errors/type' => ['version' => '1.3.0'],
    'object-inspect' => ['version' => '1.13.4'],
    'side-channel-list' => ['version' => '1.0.1'],
    'side-channel-map' => ['version' => '1.0.1'],
    'side-channel-weakmap' => ['version' => '1.0.2'],
    'get-intrinsic' => ['version' => '1.2.5'],
    'call-bound' => ['version' => '1.0.2'],
    'es-errors' => ['version' => '1.3.0'],
    'es-errors/eval' => ['version' => '1.3.0'],
    'es-errors/range' => ['version' => '1.3.0'],
    'es-errors/ref' => ['version' => '1.3.0'],
    'es-errors/syntax' => ['version' => '1.3.0'],
    'es-errors/uri' => ['version' => '1.3.0'],
    'gopd' => ['version' => '1.2.0'],
    'has-symbols' => ['version' => '1.1.0'],
    'dunder-proto/get' => ['version' => '1.0.0'],
    'call-bind-apply-helpers/functionApply' => ['version' => '1.0.0'],
    'call-bind-apply-helpers/functionCall' => ['version' => '1.0.0'],
    'function-bind' => ['version' => '1.1.2'],
    'hasown' => ['version' => '2.0.2'],
    'call-bind' => ['version' => '1.0.8'],
    'call-bind-apply-helpers' => ['version' => '1.0.0'],
    'set-function-length' => ['version' => '1.2.2'],
    'call-bind-apply-helpers/applyBind' => ['version' => '1.0.0'],
    'define-data-property' => ['version' => '1.1.4'],
    'has-property-descriptors' => ['version' => '1.0.2'],
    'instantsearch.js/es/widgets' => ['version' => '4.117.0'],
    'instantsearch-ui-components' => ['version' => '0.40.1'],
    'preact' => ['version' => '10.29.8'],
    'hogan.js' => ['version' => '3.0.2'],
    'htm/preact' => ['version' => '3.1.1'],
    'preact/hooks' => ['version' => '10.29.8'],
    'htm' => ['version' => '3.1.1'],
    'datatables.net-bs' => ['version' => '3.1.2'],
    'datatables.net' => ['version' => '3.1.3'],
    'datatables.net-bs/css/dataTables.bootstrap.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-bs4' => ['version' => '3.1.2'],
    'datatables.net-bs4/css/dataTables.bootstrap4.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-bs5' => ['version' => '3.1.3'],
    'datatables.net-bs5/css/dataTables.bootstrap5.min.css' => ['version' => '3.1.3', 'type' => 'css'],
    'datatables.net-buttons' => ['version' => '4.1.2'],
    'datatables.net-buttons-bs' => ['version' => '4.1.2'],
    'datatables.net-buttons-bs/css/buttons.bootstrap.min.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-buttons-bs4' => ['version' => '4.1.2'],
    'datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-buttons-bs5' => ['version' => '4.1.2'],
    'datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-buttons-dt' => ['version' => '4.1.2'],
    'datatables.net-dt' => ['version' => '3.1.2'],
    'datatables.net-buttons-dt/css/buttons.dataTables.min.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-dt/css/dataTables.dataTables.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-colreorder-bs' => ['version' => '3.1.2'],
    'datatables.net-colreorder' => ['version' => '3.1.2'],
    'datatables.net-colreorder-bs/css/colReorder.bootstrap.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-colreorder-bs4' => ['version' => '3.1.2'],
    'datatables.net-colreorder-bs4/css/colReorder.bootstrap4.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-colreorder-bs5' => ['version' => '3.1.2'],
    'datatables.net-colreorder-bs5/css/colReorder.bootstrap5.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-colreorder-dt' => ['version' => '3.1.2'],
    'datatables.net-colreorder-dt/css/colReorder.dataTables.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-columncontrol-bs' => ['version' => '2.1.2'],
    'datatables.net-columncontrol' => ['version' => '2.1.2'],
    'datatables.net-columncontrol-bs/css/columnControl.bootstrap.min.css' => ['version' => '2.1.2', 'type' => 'css'],
    'datatables.net-columncontrol-bs4' => ['version' => '2.1.2'],
    'datatables.net-columncontrol-bs4/css/columnControl.bootstrap4.min.css' => ['version' => '2.1.2', 'type' => 'css'],
    'datatables.net-columncontrol-bs5' => ['version' => '2.1.2'],
    'datatables.net-columncontrol-bs5/css/columnControl.bootstrap5.min.css' => ['version' => '2.1.2', 'type' => 'css'],
    'datatables.net-columncontrol-dt' => ['version' => '2.1.2'],
    'datatables.net-columncontrol-dt/css/columnControl.dataTables.min.css' => ['version' => '2.1.2', 'type' => 'css'],
    'datatables.net-fixedcolumns-bs' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-bs/css/fixedColumns.bootstrap.min.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedcolumns-bs4' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-bs4/css/fixedColumns.bootstrap4.min.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedcolumns-bs5' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.min.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedcolumns-dt' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-dt/css/fixedColumns.dataTables.min.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedheader-bs' => ['version' => '5.1.1'],
    'datatables.net-fixedheader' => ['version' => '5.1.2'],
    'datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' => ['version' => '5.1.1', 'type' => 'css'],
    'datatables.net-fixedheader-bs4' => ['version' => '5.1.1'],
    'datatables.net-fixedheader-bs4/css/fixedHeader.bootstrap4.min.css' => ['version' => '5.1.1', 'type' => 'css'],
    'datatables.net-fixedheader-bs5' => ['version' => '5.1.2'],
    'datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.min.css' => ['version' => '5.1.2', 'type' => 'css'],
    'datatables.net-fixedheader-dt' => ['version' => '5.1.1'],
    'datatables.net-fixedheader-dt/css/fixedHeader.dataTables.min.css' => ['version' => '5.1.1', 'type' => 'css'],
    'datatables.net-keytable-bs' => ['version' => '3.1.1'],
    'datatables.net-keytable' => ['version' => '3.1.1'],
    'datatables.net-keytable-bs/css/keyTable.bootstrap.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-keytable-bs4' => ['version' => '3.1.1'],
    'datatables.net-keytable-bs4/css/keyTable.bootstrap4.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-keytable-bs5' => ['version' => '3.1.1'],
    'datatables.net-keytable-bs5/css/keyTable.bootstrap5.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-keytable-dt' => ['version' => '3.1.1'],
    'datatables.net-keytable-dt/css/keyTable.dataTables.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-responsive-bs' => ['version' => '4.1.1'],
    'datatables.net-responsive' => ['version' => '4.1.1'],
    'datatables.net-responsive-bs/css/responsive.bootstrap.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-responsive-bs4' => ['version' => '4.1.1'],
    'datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-responsive-bs5' => ['version' => '4.1.1'],
    'datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-responsive-dt' => ['version' => '4.1.1'],
    'datatables.net-responsive-dt/css/responsive.dataTables.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-rowgroup-bs' => ['version' => '2.1.1'],
    'datatables.net-rowgroup' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-bs/css/rowGroup.bootstrap.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-rowgroup-bs4' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-bs4/css/rowGroup.bootstrap4.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-rowgroup-bs5' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-bs5/css/rowGroup.bootstrap5.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-rowgroup-dt' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-dt/css/rowGroup.dataTables.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-scroller-bs' => ['version' => '3.1.1'],
    'datatables.net-scroller' => ['version' => '3.1.1'],
    'datatables.net-scroller-bs/css/scroller.bootstrap.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-scroller-bs4' => ['version' => '3.1.1'],
    'datatables.net-scroller-bs4/css/scroller.bootstrap4.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-scroller-bs5' => ['version' => '3.1.1'],
    'datatables.net-scroller-bs5/css/scroller.bootstrap5.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-scroller-dt' => ['version' => '3.1.1'],
    'datatables.net-scroller-dt/css/scroller.dataTables.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-select-bs' => ['version' => '4.1.1'],
    'datatables.net-select' => ['version' => '4.1.1'],
    'datatables.net-select-bs/css/select.bootstrap.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-select-bs4' => ['version' => '4.1.1'],
    'datatables.net-select-bs4/css/select.bootstrap4.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-select-bs5' => ['version' => '4.1.1'],
    'datatables.net-select-bs5/css/select.bootstrap5.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-select-dt' => ['version' => '4.1.1'],
    'datatables.net-select-dt/css/select.dataTables.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'jszip' => ['version' => '3.10.2'],
    'lucide' => ['version' => '1.48.0'],
    'pdfmake' => ['version' => '0.3.11'],
    'pdfmake/build/vfs_fonts.js' => ['version' => '0.3.11'],
    'd3-graphviz' => ['version' => '5.6.0'],
    'd3-selection' => ['version' => '3.0.0'],
    'd3-dispatch' => ['version' => '3.0.1'],
    'd3-transition' => ['version' => '3.0.1'],
    'd3-timer' => ['version' => '3.0.1'],
    'd3-interpolate' => ['version' => '3.0.1'],
    'd3-zoom' => ['version' => '3.0.0'],
    '@hpcc-js/wasm/graphviz' => ['version' => '2.20.0'],
    'd3-format' => ['version' => '3.1.0'],
    'd3-path' => ['version' => '3.1.0'],
    'd3-color' => ['version' => '3.0.1'],
    'd3-ease' => ['version' => '3.0.1'],
    'd3-drag' => ['version' => '3.0.0'],
    'bootstrap' => ['version' => '5.3.8'],
    '@popperjs/core' => ['version' => '2.11.8'],
    'bootstrap/dist/css/bootstrap.min.css' => ['version' => '5.3.8', 'type' => 'css'],
    'datatables.net-bs5/css/dataTables.bootstrap5.css' => ['version' => '3.1.3', 'type' => 'css'],
    'datatables.net-buttons-bs5/css/buttons.bootstrap5.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-columncontrol-bs5/css/columnControl.bootstrap5.css' => ['version' => '2.1.2', 'type' => 'css'],
    'datatables.net-responsive-bs5/css/responsive.bootstrap5.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-select-bs5/css/select.bootstrap5.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-searchbuilder' => ['version' => '2.1.1'],
    'datatables.net-searchbuilder-bs5' => ['version' => '2.1.1'],
    'datatables.net-searchbuilder-bs5/css/searchBuilder.bootstrap5.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-searchbuilder-bs5/css/searchBuilder.bootstrap5.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.css' => ['version' => '5.1.2', 'type' => 'css'],
    'datatables.net-rowgroup-bs5/css/rowGroup.bootstrap5.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-plugins/i18n/en-GB.mjs' => ['version' => '3.1.2'],
    'datatables.net-plugins/i18n/es-ES.mjs' => ['version' => '3.1.2'],
    'datatables.net-plugins/i18n/de-DE.mjs' => ['version' => '3.1.2'],
];
