<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260517211901 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE babel_term (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, path VARCHAR(512) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, sort INT DEFAULT NULL, term_set_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_77FE42F2F3AD3475 ON babel_term (term_set_id)');
        $this->addSql('CREATE INDEX IDX_77FE42F2727ACA70 ON babel_term (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_code_uq ON babel_term (term_set_id, code)');
        $this->addSql('CREATE UNIQUE INDEX term_term_set_path_uq ON babel_term (term_set_id, path)');
        $this->addSql('CREATE TABLE component (id VARCHAR(128) NOT NULL, composer_name VARCHAR(255) NOT NULL, kind VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, minimum_stability VARCHAR(32) DEFAULT NULL, overview TEXT DEFAULT NULL, plan TEXT DEFAULT NULL, deprecated BOOLEAN DEFAULT false NOT NULL, status VARCHAR(255) DEFAULT NULL, local_dir VARCHAR(255) DEFAULT NULL, composer_json JSON DEFAULT NULL, pwa_yaml JSON DEFAULT NULL, last_updated_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, pending_steps JSON DEFAULT \'{}\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE fetch_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_code VARCHAR(32) NOT NULL, dataset_key VARCHAR(190) NOT NULL, kind VARCHAR(32) NOT NULL, page_number INT NOT NULL, url VARCHAR(2048) NOT NULL, status VARCHAR(32) NOT NULL, content_type VARCHAR(255) DEFAULT NULL, accept VARCHAR(255) DEFAULT NULL, archive_path VARCHAR(2048) DEFAULT NULL, record_count INT DEFAULT NULL, error VARCHAR(1024) DEFAULT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fetch_page ON fetch_page (provider_code, dataset_key, kind, page_number)');
        $this->addSql('CREATE TABLE fetch_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_code VARCHAR(32) NOT NULL, dataset_key VARCHAR(190) NOT NULL, kind VARCHAR(32) NOT NULL, row_number INT NOT NULL, source_id VARCHAR(255) DEFAULT NULL, record_type VARCHAR(32) DEFAULT NULL, payload TEXT NOT NULL, payload_bytes INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fetch_page_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FB10B11C9F2FB857 ON fetch_record (fetch_page_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_fetch_record_page_row ON fetch_record (fetch_page_id, row_number)');
        $this->addSql('CREATE TABLE site (id VARCHAR(128) NOT NULL, dokku_host VARCHAR(255) DEFAULT NULL, local_port INT DEFAULT NULL, screenshot_path VARCHAR(255) DEFAULT NULL, component_id VARCHAR(128) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_694309E4E2ABAFFF ON site (component_id)');
        $this->addSql('CREATE TABLE storage_node (id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, last_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, file_size INT DEFAULT NULL, dir_count INT DEFAULT NULL, file_count INT DEFAULT NULL, status VARCHAR(255) NOT NULL, meta JSON DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, is_dir BOOLEAN NOT NULL, is_public BOOLEAN NOT NULL, parent_id VARCHAR DEFAULT NULL, storage_id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C522350727ACA70 ON storage_node (parent_id)');
        $this->addSql('CREATE INDEX IDX_8C5223505CC5DB90 ON storage_node (storage_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STORAGE_STORAGE_PATH ON storage_node (storage_id, path)');
        $this->addSql('CREATE TABLE storage_storage (adapter VARCHAR(255) DEFAULT NULL, root VARCHAR(255) DEFAULT NULL, id VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE str (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, source_locale VARCHAR(10) NOT NULL, source TEXT NOT NULL, context VARCHAR(80) DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_ctx_idx ON str (context)');
        $this->addSql('CREATE INDEX str_src_locale_idx ON str (source_locale)');
        $this->addSql('CREATE INDEX str_src_locale_ctx_idx ON str (source_locale, context)');
        $this->addSql('CREATE UNIQUE INDEX str_code_uq ON str (code)');
        $this->addSql('CREATE TABLE str_tr (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, str_code VARCHAR(64) NOT NULL, target_locale VARCHAR(10) NOT NULL, engine VARCHAR(20) DEFAULT NULL, text TEXT DEFAULT NULL, status VARCHAR(16) DEFAULT \'new\' NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX str_tr_target_locale_idx ON str_tr (target_locale)');
        $this->addSql('CREATE INDEX str_tr_str_code_idx ON str_tr (str_code)');
        $this->addSql('CREATE UNIQUE INDEX str_tr_uq ON str_tr (str_code, target_locale, engine)');
        $this->addSql('CREATE TABLE term_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, label_code VARCHAR(64) NOT NULL, description_code VARCHAR(64) DEFAULT NULL, rules JSONB NOT NULL, meta JSONB NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX term_set_code_uq ON term_set (code)');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2F3AD3475 FOREIGN KEY (term_set_id) REFERENCES term_set (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE babel_term ADD CONSTRAINT FK_77FE42F2727ACA70 FOREIGN KEY (parent_id) REFERENCES babel_term (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fetch_record ADD CONSTRAINT FK_FB10B11C9F2FB857 FOREIGN KEY (fetch_page_id) REFERENCES fetch_page (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E4E2ABAFFF FOREIGN KEY (component_id) REFERENCES component (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE storage_node ADD CONSTRAINT FK_8C522350727ACA70 FOREIGN KEY (parent_id) REFERENCES storage_node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE storage_node ADD CONSTRAINT FK_8C5223505CC5DB90 FOREIGN KEY (storage_id) REFERENCES storage_storage (id) NOT DEFERRABLE');
        $this->addSql('DROP TABLE project');
        $this->addSql('ALTER TABLE ciine ADD pending_steps JSON DEFAULT \'{}\' NOT NULL');
        $this->addSql('ALTER TABLE index_info ADD label VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE index_info ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE index_info ADD aggregator VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE index_info ADD institution VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE index_info ADD country VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE show ADD pending_steps JSON DEFAULT \'{}\' NOT NULL');
        $this->addSql('DROP INDEX idx_75ea56e0fb7336f0');
        $this->addSql('DROP INDEX idx_75ea56e0e3bd61ce');
        $this->addSql('DROP INDEX idx_75ea56e016ba31db');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, app_json JSON DEFAULT NULL, composer_json JSON DEFAULT NULL, pwa_yaml JSON DEFAULT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(255) DEFAULT NULL, local_dir VARCHAR(255) DEFAULT NULL, minimum_stability VARCHAR(6) DEFAULT NULL, last_updated_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2F3AD3475');
        $this->addSql('ALTER TABLE babel_term DROP CONSTRAINT FK_77FE42F2727ACA70');
        $this->addSql('ALTER TABLE fetch_record DROP CONSTRAINT FK_FB10B11C9F2FB857');
        $this->addSql('ALTER TABLE site DROP CONSTRAINT FK_694309E4E2ABAFFF');
        $this->addSql('ALTER TABLE storage_node DROP CONSTRAINT FK_8C522350727ACA70');
        $this->addSql('ALTER TABLE storage_node DROP CONSTRAINT FK_8C5223505CC5DB90');
        $this->addSql('DROP TABLE babel_term');
        $this->addSql('DROP TABLE component');
        $this->addSql('DROP TABLE fetch_page');
        $this->addSql('DROP TABLE fetch_record');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE storage_node');
        $this->addSql('DROP TABLE storage_storage');
        $this->addSql('DROP TABLE str');
        $this->addSql('DROP TABLE str_tr');
        $this->addSql('DROP TABLE term_set');
        $this->addSql('ALTER TABLE ciine DROP pending_steps');
        $this->addSql('ALTER TABLE index_info DROP label');
        $this->addSql('ALTER TABLE index_info DROP description');
        $this->addSql('ALTER TABLE index_info DROP aggregator');
        $this->addSql('ALTER TABLE index_info DROP institution');
        $this->addSql('ALTER TABLE index_info DROP country');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE show DROP pending_steps');
    }
}
